### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by karmarcharger** [mlfunston/node-red-contrib-broadlink#22]
Hi, I recently started using the Broadlink RM4 Pro, and was able to discover it via the discover node, however it had an error message in the payload.
![image](https://user-images.githubusercontent.com/10364143/77079677-5929a800-6a33-11ea-9dfd-217db21125b1.png)
I added the device to the RM node from the learning example
![image](https://user-images.githubusercontent.com/10364143/77079855-955d0880-6a33-11ea-8bb9-d887d2fc3bc1.png)
However when i ran the payload and kept pressing my remote button aiming at the RM4 Pro nothing was outputted to the payload.

May I know what I am doing wrong? or is the RM4 Pro not compatible with the node?

*Note the RM4 Pro is already configured via the Broadlink Application

Thank you for taking your time to read this.

**Comment by karmarcharger** [comment]
*Note the RM4 Pro is already configured via the Broadlink Application

**Comment by mlfunston** [comment]
Looks like it's a new device that isn't tested with the node. I'll add the device type and you can test it and see. I'll do an update in a couple of days.

**Comment by mlfunston** [comment]
@karmarcharger - I have published a new version 1.0.8 to NPM with a possible fix for this. It may need some extra work though. Can you see if the unit is discovered now with the updated version?
There may be some extra headers needed for this new version. Also if you have added it to the cloud service, you may need to reset the unit.

**Comment by karmarcharger** [comment]
![image](https://user-images.githubusercontent.com/10364143/77280585-b35e8d80-6cff-11ea-863d-723043ebc9b0.png)
Yes the unit is known now, however when I use the example template to learn signals it returns timeout despite me spamming the RC button on the device.

Also the temperature function in the RM returns timeout as shown above.
Below are the settings I have for the RM learn nodes and RM Temperature node.
![image](https://user-images.githubusercontent.com/10364143/77280705-ffa9cd80-6cff-11ea-82ae-ab9fdafe333f.png)
![image](https://user-images.githubusercontent.com/10364143/77280713-08020880-6d00-11ea-93f9-076abe9ded32.png)
![image](https://user-images.githubusercontent.com/10364143/77280730-105a4380-6d00-11ea-8149-4d942956543c.png)
* I have also tested with the new RM Reciever node, recieved timeout object.
![image](https://user-images.githubusercontent.com/10364143/77281192-6380c600-6d01-11ea-8c82-1eb7be31ddbf.png)

**Comment by mlfunston** [comment]
Looks like the new headers I mentioned will be required and I'll add them and release an update soon.

**Comment by mlfunston** [comment]
Have published a new version, please try that one out as it provides updates to the newer RM types.

**Comment by karmarcharger** [comment]
![image](https://user-images.githubusercontent.com/10364143/78401868-35b64e00-762c-11ea-8b7b-2aa88482b7d3.png)
Tested the new version 2.0.0, still getting timeouts when using the sample learn code
![image](https://user-images.githubusercontent.com/10364143/78401942-5e3e4800-762c-11ea-8c1d-8aa2b2bdde9e.png)
I am using the Type ID obtained from the discover node.
![image](https://user-images.githubusercontent.com/10364143/78402045-862dab80-762c-11ea-9dfd-ac7895e4730b.png)

The Sharedfiles folder i found in the broadlink app from my iphone contains only 1 folder ConCode
![image](https://user-images.githubusercontent.com/10364143/78406242-cf81f900-7634-11ea-8d19-06ebb820681b.png)
This is the app i am using https://apps.apple.com/us/app/broadlink/id1450257910

@mlfunston
